# Student Placement

## Import Labrary

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,r2_score,classification_report

import pickle

In [3]:
df=pd.read_csv('students_placement.csv')
df

cgpa   iq  profile_score  placed
0    5.97  106             61       0
1    6.83  113             77       0
2    6.60  110             61       0
3    5.54  113             68       0
4    6.84  102             67       0
..    ...  ...            ...     ...
295  6.44  107             54       0
296  6.09  108             52       0
297  7.68  101             70       1
298  7.00   90             28       1
299  4.79  118             70       0

[300 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   cgpa           300 non-null    float64
 1   iq             300 non-null    int64  
 2   profile_score  300 non-null    int64  
 3   placed         300 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 9.5 KB


In [5]:
df['placed'].value_counts()

1    152
0    148
Name: placed, dtype: int64

In [6]:
x=df.drop(['placed'],axis=1)
y=df['placed']
x
y

0      0
1      0
2      0
3      0
4      0
      ..
295    0
296    0
297    1
298    1
299    0
Name: placed, Length: 300, dtype: int64

## Train Test Split

In [7]:
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2,random_state=10,)
x_test

cgpa   iq  profile_score
24   5.51  112             51
65   8.41  100             58
113  8.25   92             67
261  7.51   90             69
188  6.97  101             68
181  6.17  115             52
59   6.45  107             63
87   5.33  103             75
293  6.86  110             63
277  5.19  116             86
244  6.49  108             45
43   6.34  105             62
193  8.37  107             58
284  7.06   93             44
238  8.29   89             70
26   7.73   90             68
245  8.52   99             58
214  5.80  107             92
189  6.04  104             30
281  7.60  103             64
52   6.56  104             77
215  7.00  104             48
130  6.69   93             72
64   7.50  102             59
164  6.02  107             69
70   6.02  121             27
138  8.80   83             62
202  4.97  116             72
230  9.05   94             67
132  6.99  116             63
47   8.09   97             80
151  5.70  118             65
25   7.19   97             47
183  6.69  104             74
197  6.32  107             68
298  7.00   90             28
276  6.89  104             81
98   7.27   91             70
231  6.02  107             74
76   6.99   94             73
129  5.80  116             50
167  5.13  114             83
270  5.51  114             51
100  8.35   98             71
191  5.34  104             98
199  5.67  111             69
139  7.54   96             71
106  5.61  108             74
36   7.93   94             53
10   7.64  102             51
273  8.13   91             35
111  5.67  112             67
286  6.98  105             54
119  5.54  118             60
280  6.85  102             67
195  7.97   96             76
237  7.12  107             62
80   5.29  103             83
172  6.62   96             37
56   5.31  116             51

## Model Training

### Logistic Regression

In [21]:
lg_model=LogisticRegressionCV()
lg_model.fit(x_train,y_train)

LogisticRegressionCV()

## Evalution Part

In [24]:
#accuracy on testing data

y_pred=lg_model.predict(x_test)

conf_matrix=confusion_matrix(y_test,y_pred)
print("confusion matrix\n",conf_matrix)

acc_scroe=accuracy_score(y_test,y_pred)
print("accuracy score\n",acc_scroe)

clss_report=classification_report(y_test,y_pred)
print("classification report\n",clss_report)

confusion matrix
 [[29  3]
 [ 5 23]]
accuracy score
 0.8666666666666667
classification report
               precision    recall  f1-score   support

           0       0.85      0.91      0.88        32
           1       0.88      0.82      0.85        28

    accuracy                           0.87        60
   macro avg       0.87      0.86      0.87        60
weighted avg       0.87      0.87      0.87        60



In [25]:
#accuracy on trainig data

y_pred_train=lg_model.predict(x_train)

conf_matrix=confusion_matrix(y_train,y_pred_train)
print("confusion matrix\n",conf_matrix)

acc_scroe=accuracy_score(y_train,y_pred_train)
print("accuracy score\n",acc_scroe)

clss_report=classification_report(y_train,y_pred_train)
print("classification report\n",clss_report)

confusion matrix
 [[103  13]
 [ 16 108]]
accuracy score
 0.8791666666666667
classification report
               precision    recall  f1-score   support

           0       0.87      0.89      0.88       116
           1       0.89      0.87      0.88       124

    accuracy                           0.88       240
   macro avg       0.88      0.88      0.88       240
weighted avg       0.88      0.88      0.88       240



### Random forest

In [26]:
Rf_model=RandomForestClassifier()
Rf_model.fit(x_train,y_train)

RandomForestClassifier()

In [27]:
#accuracy on testing data

y_pred=Rf_model.predict(x_test)

conf_matrix=confusion_matrix(y_test,y_pred)
print("confusion matrix\n",conf_matrix)

acc_scroe=accuracy_score(y_test,y_pred)
print("accuracy score\n",acc_scroe)

clss_report=classification_report(y_test,y_pred)
print("classification report\n",clss_report)

confusion matrix
 [[27  5]
 [ 5 23]]
accuracy score
 0.8333333333333334
classification report
               precision    recall  f1-score   support

           0       0.84      0.84      0.84        32
           1       0.82      0.82      0.82        28

    accuracy                           0.83        60
   macro avg       0.83      0.83      0.83        60
weighted avg       0.83      0.83      0.83        60



In [28]:
#accuracy on trainig data

y_pred_train=Rf_model.predict(x_train)

conf_matrix=confusion_matrix(y_train,y_pred_train)
print("confusion matrix\n",conf_matrix)

acc_scroe=accuracy_score(y_train,y_pred_train)
print("accuracy score\n",acc_scroe)

clss_report=classification_report(y_train,y_pred_train)
print("classification report\n",clss_report)

confusion matrix
 [[116   0]
 [  0 124]]
accuracy score
 1.0
classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       116
           1       1.00      1.00      1.00       124

    accuracy                           1.00       240
   macro avg       1.00      1.00      1.00       240
weighted avg       1.00      1.00      1.00       240



In [29]:
with open ('model.pkl','wb')as f:
    pickle.dump(lg_model,f)